// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.Role)
	return err
}

const createConversation = `-- name: CreateConversation :one

INSERT INTO conversations (type, name)
VALUES ($1, $2)
RETURNING id, type, name, created_at, updated_at
`

type CreateConversationParams struct {
	Type string         `json:"type"`
	Name sql.NullString `json:"name"`
}

// =====================================================
// sqlc/queries/chat.sql
// Queries for WhatsApp-style Chat (conversations, members, messages)
// =====================================================
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation, arg.Type, arg.Name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDirectConversation = `-- name: FindDirectConversation :one
SELECT c.id, c.type, c.name, c.created_at, c.updated_at
FROM conversations c
JOIN conversation_members cm1 ON cm1.conversation_id = c.id
JOIN conversation_members cm2 ON cm2.conversation_id = c.id
WHERE c.type = 'direct'
  AND cm1.user_id = $1
  AND cm2.user_id = $2
LIMIT 1
`

type FindDirectConversationParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, findDirectConversation, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, type, name, created_at, updated_at
FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, sender_id, message_type, content, media_url, media_metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, sender_id, message_type, content, media_url, media_metadata, created_at, deleted_at
`

type InsertMessageParams struct {
	ConversationID uuid.UUID       `json:"conversation_id"`
	SenderID       uuid.UUID       `json:"sender_id"`
	MessageType    string          `json:"message_type"`
	Content        sql.NullString  `json:"content"`
	MediaUrl       sql.NullString  `json:"media_url"`
	MediaMetadata  json.RawMessage `json:"media_metadata"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, insertMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.MessageType,
		arg.Content,
		arg.MediaUrl,
		arg.MediaMetadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.MessageType,
		&i.Content,
		&i.MediaUrl,
		&i.MediaMetadata,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isConversationMember = `-- name: IsConversationMember :one
SELECT EXISTS (
    SELECT 1 FROM conversation_members
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsConversationMemberParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IsConversationMember(ctx context.Context, arg IsConversationMemberParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isConversationMember, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT cm.conversation_id, cm.user_id, cm.role, cm.joined_at, cm.last_read_at,
       u.username, u.display_name, u.avatar_url
FROM conversation_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.conversation_id = $1
ORDER BY cm.joined_at ASC
`

type ListConversationMembersRow struct {
	ConversationID uuid.UUID      `json:"conversation_id"`
	UserID         uuid.UUID      `json:"user_id"`
	Role           string         `json:"role"`
	JoinedAt       time.Time      `json:"joined_at"`
	LastReadAt     time.Time      `json:"last_read_at"`
	Username       string         `json:"username"`
	DisplayName    sql.NullString `json:"display_name"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID uuid.UUID) ([]ListConversationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationMembersRow{}
	for rows.Next() {
		var i ListConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.sender_id, m.message_type, m.content, m.media_url, m.media_metadata, m.created_at,
       u.username AS sender_username, u.display_name AS sender_display_name, u.avatar_url AS sender_avatar_url
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1
  AND m.deleted_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (m.created_at, m.id) < ($2::timestamptz, $3::uuid))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type ListMessagesParams struct {
	ConversationID uuid.UUID     `json:"conversation_id"`
	CursorCreated  sql.NullTime  `json:"cursor_created"`
	CursorID       uuid.NullUUID `json:"cursor_id"`
	PageLimit      int32         `json:"page_limit"`
}

type ListMessagesRow struct {
	ID                uuid.UUID       `json:"id"`
	ConversationID    uuid.UUID       `json:"conversation_id"`
	SenderID          uuid.UUID       `json:"sender_id"`
	MessageType       string          `json:"message_type"`
	Content           sql.NullString  `json:"content"`
	MediaUrl          sql.NullString  `json:"media_url"`
	MediaMetadata     json.RawMessage `json:"media_metadata"`
	CreatedAt         time.Time       `json:"created_at"`
	SenderUsername    string          `json:"sender_username"`
	SenderDisplayName sql.NullString  `json:"sender_display_name"`
	SenderAvatarUrl   sql.NullString  `json:"sender_avatar_url"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.ConversationID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.MessageType,
			&i.Content,
			&i.MediaUrl,
			&i.MediaMetadata,
			&i.CreatedAt,
			&i.SenderUsername,
			&i.SenderDisplayName,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.type, c.name, c.created_at, c.updated_at,
       cm.last_read_at,
       COALESCE(m.id, '00000000-0000-0000-0000-000000000000'::uuid) AS last_message_id,
       COALESCE(m.sender_id, '00000000-0000-0000-0000-000000000000'::uuid) AS last_message_sender_id,
       COALESCE(m.message_type, '') AS last_message_type,
       COALESCE(m.content, '') AS last_message_content,
       COALESCE(m.created_at, '1970-01-01 00:00:00Z'::timestamptz) AS last_message_created_at
FROM conversations c
JOIN conversation_members cm ON cm.conversation_id = c.id
LEFT JOIN LATERAL (
    SELECT id, sender_id, message_type, content, created_at
    FROM messages
    WHERE conversation_id = c.id AND deleted_at IS NULL
    ORDER BY created_at DESC
    LIMIT 1
) m ON true
WHERE cm.user_id = $1
  AND ($2::timestamptz IS NULL
       OR (c.updated_at, c.id) < ($2::timestamptz, $3::uuid))
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $4
`

type ListUserConversationsParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	CursorUpdated sql.NullTime  `json:"cursor_updated"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListUserConversationsRow struct {
	ID                   uuid.UUID      `json:"id"`
	Type                 string         `json:"type"`
	Name                 sql.NullString `json:"name"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	LastReadAt           time.Time      `json:"last_read_at"`
	LastMessageID        uuid.UUID      `json:"last_message_id"`
	LastMessageSenderID  uuid.UUID      `json:"last_message_sender_id"`
	LastMessageType      string         `json:"last_message_type"`
	LastMessageContent   string         `json:"last_message_content"`
	LastMessageCreatedAt time.Time      `json:"last_message_created_at"`
}

func (q *Queries) ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]ListUserConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserConversations,
		arg.UserID,
		arg.CursorUpdated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastReadAt,
			&i.LastMessageID,
			&i.LastMessageSenderID,
			&i.LastMessageType,
			&i.LastMessageContent,
			&i.LastMessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchConversationUpdatedAt = `-- name: TouchConversationUpdatedAt :exec
UPDATE conversations
SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchConversationUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchConversationUpdatedAt, id)
	return err
}

const updateLastReadAt = `-- name: UpdateLastReadAt :exec
UPDATE conversation_members
SET last_read_at = NOW()
WHERE conversation_id = $1 AND user_id = $2
`

type UpdateLastReadAtParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateLastReadAt(ctx context.Context, arg UpdateLastReadAtParams) error {
	_, err := q.db.ExecContext(ctx, updateLastReadAt, arg.ConversationID, arg.UserID)
	return err
}
