// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countCommentSubtree = `-- name: CountCommentSubtree :one
WITH RECURSIVE subtree AS (
    SELECT c.id FROM comments c WHERE c.id = $1
    UNION ALL
    SELECT c.id FROM comments c
    JOIN subtree s ON c.parent_id = s.id
)
SELECT COUNT(*)::int FROM subtree
`

// Recursive CTE counting this comment + all descendants.
// Used before deletion to know how much to decrement
// the video's comments_count.
func (q *Queries) CountCommentSubtree(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCommentSubtree, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteCommentByID = `-- name: DeleteCommentByID :exec
DELETE FROM comments WHERE id = $1
`

// ON DELETE CASCADE handles replies automatically.
func (q *Queries) DeleteCommentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommentByID, id)
	return err
}

const deleteCommentsByUser = `-- name: DeleteCommentsByUser :exec
DELETE FROM comments WHERE user_id = $1
`

func (q *Queries) DeleteCommentsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommentsByUser, userID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.video_id, c.user_id, c.parent_id, c.content, c.created_at, u.username, u.display_name, u.avatar_url, u.is_private
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
LIMIT 1
`

type GetCommentByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	VideoID     uuid.UUID      `json:"video_id"`
	UserID      uuid.UUID      `json:"user_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Content     string         `json:"content"`
	CreatedAt   time.Time      `json:"created_at"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsPrivate,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :one

INSERT INTO comments (video_id, user_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, user_id, parent_id, content, created_at
`

type InsertCommentParams struct {
	VideoID  uuid.UUID     `json:"video_id"`
	UserID   uuid.UUID     `json:"user_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Content  string        `json:"content"`
}

// =====================================================
// queries/comments.sql
// Comments + recursive subtree count. See users.sql header.
// =====================================================
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.VideoID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByVideo = `-- name: ListCommentsByVideo :many
SELECT
    c.id,
    c.video_id,
    c.user_id,
    c.parent_id,
    c.content,
    c.created_at,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.video_id = $1
  AND ($2::timestamptz IS NULL
       OR (c.created_at, c.id) < ($2::timestamptz, $3::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4
`

type ListCommentsByVideoParams struct {
	VideoID       uuid.UUID     `json:"video_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListCommentsByVideoRow struct {
	ID          uuid.UUID      `json:"id"`
	VideoID     uuid.UUID      `json:"video_id"`
	UserID      uuid.UUID      `json:"user_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Content     string         `json:"content"`
	CreatedAt   time.Time      `json:"created_at"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
}

// Flat list of comments for a video, cursor pagination.
// Joins user for author info.
func (q *Queries) ListCommentsByVideo(ctx context.Context, arg ListCommentsByVideoParams) ([]ListCommentsByVideoRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByVideo,
		arg.VideoID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByVideoRow{}
	for rows.Next() {
		var i ListCommentsByVideoRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
