// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follows.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type DeleteFollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.FollowerID, arg.FolloweeID)
	return err
}

const deleteFollowsByFollowee = `-- name: DeleteFollowsByFollowee :exec
DELETE FROM follows WHERE followee_id = $1
`

func (q *Queries) DeleteFollowsByFollowee(ctx context.Context, followeeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsByFollowee, followeeID)
	return err
}

const deleteFollowsByFollower = `-- name: DeleteFollowsByFollower :exec
DELETE FROM follows WHERE follower_id = $1
`

func (q *Queries) DeleteFollowsByFollower(ctx context.Context, followerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsByFollower, followerID)
	return err
}

const followUser = `-- name: FollowUser :exec

INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

// =====================================================
// queries/follows.sql
// Follow relations. See sqlc/queries/users.sql header.
// =====================================================
// Idempotent insert. ON CONFLICT DO NOTHING makes it safe
// to call even if the follow already exists.
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const getFollow = `-- name: GetFollow :one
SELECT follower_id, followee_id, created_at
FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type GetFollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

// Returns the row (including created_at) for a given
// (follower, followee) pair, or sql.ErrNoRows when the
// follow does not exist. Used by the follow handler to
// return the wire `created_at` after an idempotent
// INSERT (which is ON CONFLICT DO NOTHING and therefore
// cannot RETURNING the original row).
func (q *Queries) GetFollow(ctx context.Context, arg GetFollowParams) (Follow, error) {
	row := q.db.QueryRowContext(ctx, getFollow, arg.FollowerID, arg.FolloweeID)
	var i Follow
	err := row.Scan(&i.FollowerID, &i.FolloweeID, &i.CreatedAt)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND followee_id = $2
)
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFollowers = `-- name: ListFollowers :many
SELECT
    f.follower_id AS id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private,
    f.created_at,
    EXISTS (
        SELECT 1 FROM follows f2
        WHERE f2.follower_id = $1 AND f2.followee_id = f.follower_id
    ) AS is_following_back
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $2
  AND ($3::timestamptz IS NULL
       OR (f.created_at, f.follower_id) < ($3::timestamptz, $4::uuid))
ORDER BY f.created_at DESC, f.follower_id DESC
LIMIT $5
`

type ListFollowersParams struct {
	FollowerID    uuid.UUID     `json:"follower_id"`
	FolloweeID    uuid.UUID     `json:"followee_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListFollowersRow struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	DisplayName     sql.NullString `json:"display_name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	IsPrivate       bool           `json:"is_private"`
	CreatedAt       time.Time      `json:"created_at"`
	IsFollowingBack bool           `json:"is_following_back"`
}

// Returns followers of followee_id with user profile fields.
// Cursor pagination: (f.created_at, f.follower_id) < ($3, $4).
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers,
		arg.FollowerID,
		arg.FolloweeID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.IsFollowingBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
    f.followee_id AS id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private,
    f.created_at
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $1
  AND ($2::timestamptz IS NULL
       OR (f.created_at, f.followee_id) < ($2::timestamptz, $3::uuid))
ORDER BY f.created_at DESC, f.followee_id DESC
LIMIT $4
`

type ListFollowingParams struct {
	FollowerID    uuid.UUID     `json:"follower_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListFollowingRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Returns users that follower_id is following.
func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing,
		arg.FollowerID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
