// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteLike = `-- name: DeleteLike :one
DELETE FROM likes
WHERE user_id = $1 AND video_id = $2
RETURNING user_id, video_id, created_at
`

type DeleteLikeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, deleteLike, arg.UserID, arg.VideoID)
	var i Like
	err := row.Scan(&i.UserID, &i.VideoID, &i.CreatedAt)
	return i, err
}

const deleteLikesByUser = `-- name: DeleteLikesByUser :exec
DELETE FROM likes WHERE user_id = $1
`

func (q *Queries) DeleteLikesByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLikesByUser, userID)
	return err
}

const insertLike = `-- name: InsertLike :one

INSERT INTO likes (user_id, video_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING user_id, video_id, created_at
`

type InsertLikeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

// =====================================================
// queries/likes.sql
// Like / unlike. See sqlc/queries/users.sql header.
// =====================================================
func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, insertLike, arg.UserID, arg.VideoID)
	var i Like
	err := row.Scan(&i.UserID, &i.VideoID, &i.CreatedAt)
	return i, err
}

const isLiked = `-- name: IsLiked :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE user_id = $1 AND video_id = $2
)
`

type IsLikedParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) IsLiked(ctx context.Context, arg IsLikedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isLiked, arg.UserID, arg.VideoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
