// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID     `json:"id"`
	VideoID   uuid.UUID     `json:"video_id"`
	UserID    uuid.UUID     `json:"user_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
}

type Conversation struct {
	ID        uuid.UUID      `json:"id"`
	Type      string         `json:"type"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type ConversationMember struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
	Role           string    `json:"role"`
	JoinedAt       time.Time `json:"joined_at"`
	LastReadAt     time.Time `json:"last_read_at"`
}

type Follow struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Like struct {
	UserID    uuid.UUID `json:"user_id"`
	VideoID   uuid.UUID `json:"video_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID       `json:"id"`
	ConversationID uuid.UUID       `json:"conversation_id"`
	SenderID       uuid.UUID       `json:"sender_id"`
	MessageType    string          `json:"message_type"`
	Content        sql.NullString  `json:"content"`
	MediaUrl       sql.NullString  `json:"media_url"`
	MediaMetadata  json.RawMessage `json:"media_metadata"`
	CreatedAt      time.Time       `json:"created_at"`
	DeletedAt      sql.NullTime    `json:"deleted_at"`
}

type Notification struct {
	ID        uuid.UUID       `json:"id"`
	UserID    uuid.UUID       `json:"user_id"`
	ActorID   uuid.UUID       `json:"actor_id"`
	Type      string          `json:"type"`
	Payload   json.RawMessage `json:"payload"`
	IsRead    bool            `json:"is_read"`
	CreatedAt time.Time       `json:"created_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	ZitadelID   string         `json:"zitadel_id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
	IsActive    bool           `json:"is_active"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Video struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	R2Key           string         `json:"r2_key"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	RetryCount      int32          `json:"retry_count"`
	LikesCount      int32          `json:"likes_count"`
	ViewsCount      int32          `json:"views_count"`
	CommentsCount   int32          `json:"comments_count"`
	CreatedAt       time.Time      `json:"created_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}
