// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteNotificationsByActor = `-- name: DeleteNotificationsByActor :exec
DELETE FROM notifications WHERE actor_id = $1
`

func (q *Queries) DeleteNotificationsByActor(ctx context.Context, actorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByActor, actorID)
	return err
}

const deleteNotificationsForUser = `-- name: DeleteNotificationsForUser :exec
DELETE FROM notifications WHERE user_id = $1
`

func (q *Queries) DeleteNotificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsForUser, userID)
	return err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (user_id, actor_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, actor_id, type, payload, is_read, created_at
`

type InsertNotificationParams struct {
	UserID  uuid.UUID       `json:"user_id"`
	ActorID uuid.UUID       `json:"actor_id"`
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload"`
}

// =====================================================
// queries/notifications.sql
// In-app notifications. See sqlc/queries/users.sql header.
// =====================================================
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, actor_id, type, payload, is_read, created_at
FROM notifications
WHERE user_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// All notifications for a user, newest first, cursor pagination.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.UserID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
