// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const confirmVideoProcessing = `-- name: ConfirmVideoProcessing :one
UPDATE videos
SET status = 'PROCESSING', retry_count = 0
WHERE id = $1
  AND user_id = $2
  AND status = 'PENDING_UPLOAD'
  AND r2_key = $3
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type ConfirmVideoProcessingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	R2Key  string    `json:"r2_key"`
}

// Atomic transition PENDING_UPLOAD -> PROCESSING. Returns
// the updated row only when the ownership + r2_key + status
// all match. Used by POST /api/videos/confirm.
func (q *Queries) ConfirmVideoProcessing(ctx context.Context, arg ConfirmVideoProcessingParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, confirmVideoProcessing, arg.ID, arg.UserID, arg.R2Key)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countCommentSubtree = `-- name: CountCommentSubtree :one
WITH RECURSIVE subtree AS (
    SELECT c.id FROM comments c WHERE c.id = $1
    UNION ALL
    SELECT c.id FROM comments c
    JOIN subtree s ON c.parent_id = s.id
)
SELECT COUNT(*)::int FROM subtree
`

// Recursive CTE counting this comment + all descendants.
// Used before deletion to know how much to decrement
// the video's comments_count.
func (q *Queries) CountCommentSubtree(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countCommentSubtree, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (zitadel_id, username, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (zitadel_id) DO NOTHING
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

type CreateUserParams struct {
	ZitadelID   string         `json:"zitadel_id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
}

// get-or-create: on conflict do nothing. Caller re-selects
// the row when INSERT returns nothing.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ZitadelID, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active  = FALSE,
    deleted_at = COALESCE(deleted_at, NOW())
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

// Triggered by webhook event user.deactivated.
func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const decrementCommentsCount = `-- name: DecrementCommentsCount :exec
UPDATE videos
SET comments_count = comments_count - 1
WHERE id = $1 AND comments_count > 0
`

func (q *Queries) DecrementCommentsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCommentsCount, id)
	return err
}

const decrementCommentsForUser = `-- name: DecrementCommentsForUser :exec
UPDATE videos
SET comments_count = GREATEST(comments_count - 1, 0)
WHERE id IN (
    SELECT c.video_id FROM comments c WHERE c.user_id = $1
)
`

func (q *Queries) DecrementCommentsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCommentsForUser, userID)
	return err
}

const decrementLikesCount = `-- name: DecrementLikesCount :exec
UPDATE videos
SET likes_count = likes_count - 1
WHERE id = $1 AND likes_count > 0
`

// Called inside the same tx as DELETE FROM likes. Guarded
// by >= 1 to keep the chk_videos_counters check happy.
func (q *Queries) DecrementLikesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementLikesCount, id)
	return err
}

const decrementLikesForUser = `-- name: DecrementLikesForUser :exec
UPDATE videos
SET likes_count = GREATEST(likes_count - 1, 0)
WHERE id IN (SELECT l.video_id FROM likes l WHERE l.user_id = $1)
`

// Called by DeleteUserData to keep the denormalized
// counter accurate after a user is tombstoned.
func (q *Queries) DecrementLikesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementLikesForUser, userID)
	return err
}

const deleteCommentByID = `-- name: DeleteCommentByID :exec
DELETE FROM comments WHERE id = $1
`

// ON DELETE CASCADE handles replies automatically.
func (q *Queries) DeleteCommentByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommentByID, id)
	return err
}

const deleteCommentsByUser = `-- name: DeleteCommentsByUser :exec
DELETE FROM comments WHERE user_id = $1
`

func (q *Queries) DeleteCommentsByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCommentsByUser, userID)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type DeleteFollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.FollowerID, arg.FolloweeID)
	return err
}

const deleteFollowsByFollowee = `-- name: DeleteFollowsByFollowee :exec
DELETE FROM follows WHERE followee_id = $1
`

func (q *Queries) DeleteFollowsByFollowee(ctx context.Context, followeeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsByFollowee, followeeID)
	return err
}

const deleteFollowsByFollower = `-- name: DeleteFollowsByFollower :exec
DELETE FROM follows WHERE follower_id = $1
`

func (q *Queries) DeleteFollowsByFollower(ctx context.Context, followerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsByFollower, followerID)
	return err
}

const deleteLike = `-- name: DeleteLike :one
DELETE FROM likes
WHERE user_id = $1 AND video_id = $2
RETURNING user_id, video_id, created_at
`

type DeleteLikeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, deleteLike, arg.UserID, arg.VideoID)
	var i Like
	err := row.Scan(&i.UserID, &i.VideoID, &i.CreatedAt)
	return i, err
}

const deleteLikesByUser = `-- name: DeleteLikesByUser :exec
DELETE FROM likes WHERE user_id = $1
`

func (q *Queries) DeleteLikesByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLikesByUser, userID)
	return err
}

const deleteNotificationsByActor = `-- name: DeleteNotificationsByActor :exec
DELETE FROM notifications WHERE actor_id = $1
`

func (q *Queries) DeleteNotificationsByActor(ctx context.Context, actorID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByActor, actorID)
	return err
}

const deleteNotificationsForUser = `-- name: DeleteNotificationsForUser :exec
DELETE FROM notifications WHERE user_id = $1
`

func (q *Queries) DeleteNotificationsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsForUser, userID)
	return err
}

const deleteVideoRow = `-- name: DeleteVideoRow :exec
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideoRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideoRow, id)
	return err
}

const deleteVideosByUser = `-- name: DeleteVideosByUser :exec
DELETE FROM videos WHERE user_id = $1
`

// Called from DeleteUserData AFTER the r2 keys are
// enqueued for cleanup. videos.user_id has ON DELETE
// CASCADE so this is mostly defensive.
func (q *Queries) DeleteVideosByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideosByUser, userID)
	return err
}

const followUser = `-- name: FollowUser :exec

INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

// =====================================================
// follows
// =====================================================
// Idempotent insert. ON CONFLICT DO NOTHING makes it safe
// to call even if the follow already exists.
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.video_id, c.user_id, c.parent_id, c.content, c.created_at, u.username, u.display_name, u.avatar_url, u.is_private
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.id = $1
LIMIT 1
`

type GetCommentByIDRow struct {
	ID          uuid.UUID      `json:"id"`
	VideoID     uuid.UUID      `json:"video_id"`
	UserID      uuid.UUID      `json:"user_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Content     string         `json:"content"`
	CreatedAt   time.Time      `json:"created_at"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsPrivate,
	)
	return i, err
}

const getPendingVideoByUser = `-- name: GetPendingVideoByUser :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE user_id = $1 AND status = 'PENDING_UPLOAD'
LIMIT 1
`

// Used by upload-intent to reuse / replace an existing
// PENDING_UPLOAD record.
func (q *Queries) GetPendingVideoByUser(ctx context.Context, userID uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getPendingVideoByUser, userID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByZitadelID = `-- name: GetUserByZitadelID :one


SELECT id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
FROM users
WHERE zitadel_id = $1
LIMIT 1
`

// =====================================================
// queries.sql
// Type-safe data access for the TikTok clone backend.
// Consumed by sqlc. One file = one source of truth for
// every SELECT/INSERT/UPDATE/DELETE issued by the app.
// No raw SQL is allowed in handlers (LLD_PLAN.md).
// =====================================================
// =====================================================
// users
// =====================================================
// Used by the auth middleware get-or-create flow.
func (q *Queries) GetUserByZitadelID(ctx context.Context, zitadelID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByZitadelID, zitadelID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProfileWithStats = `-- name: GetUserProfileWithStats :one
SELECT
    u.id, u.zitadel_id, u.username, u.display_name, u.bio, u.avatar_url, u.is_private, u.is_active, u.deleted_at, u.created_at,
    (SELECT COUNT(*) FROM follows f WHERE f.followee_id = u.id) AS follower_count,
    (SELECT COUNT(*) FROM follows f WHERE f.follower_id = u.id) AS following_count,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $2 AND f.followee_id = u.id
    ) AS is_following
FROM users u
WHERE u.id = $1
LIMIT 1
`

type GetUserProfileWithStatsParams struct {
	ID         uuid.UUID `json:"id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

type GetUserProfileWithStatsRow struct {
	ID             uuid.UUID      `json:"id"`
	ZitadelID      string         `json:"zitadel_id"`
	Username       string         `json:"username"`
	DisplayName    sql.NullString `json:"display_name"`
	Bio            sql.NullString `json:"bio"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	IsPrivate      bool           `json:"is_private"`
	IsActive       bool           `json:"is_active"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	FollowerCount  int64          `json:"follower_count"`
	FollowingCount int64          `json:"following_count"`
	IsFollowing    bool           `json:"is_following"`
}

// Profile + follower/following counts + is_following for
// the requesting viewer. Returns NULL for
// is_following when the viewer is the same as the
// profile owner.
func (q *Queries) GetUserProfileWithStats(ctx context.Context, arg GetUserProfileWithStatsParams) (GetUserProfileWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileWithStats, arg.ID, arg.FollowerID)
	var i GetUserProfileWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.IsFollowing,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByIDForUpdate = `-- name: GetVideoByIDForUpdate :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE id = $1
FOR UPDATE
`

// Caller MUST be inside a transaction.
func (q *Queries) GetVideoByIDForUpdate(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByIDForUpdate, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoDetail = `-- name: GetVideoDetail :one
SELECT
    v.id, v.user_id, v.title, v.description, v.r2_key, v.hls_prefix, v.thumbnail_key, v.duration_seconds, v.status, v.retry_count, v.likes_count, v.views_count, v.comments_count, v.created_at, v.deleted_at,
    u.id            AS user_id_2,
    u.zitadel_id    AS user_zitadel_id,
    u.username      AS user_username,
    u.display_name  AS user_display_name,
    u.avatar_url    AS user_avatar_url,
    u.is_private    AS user_is_private,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.video_id = v.id AND l.user_id = $2
    ) AS liked_by_me
FROM videos v
JOIN users u ON u.id = v.user_id
WHERE v.id = $1
LIMIT 1
`

type GetVideoDetailParams struct {
	ID       uuid.UUID     `json:"id"`
	ViewerID uuid.NullUUID `json:"viewer_id"`
}

type GetVideoDetailRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	R2Key           string         `json:"r2_key"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	RetryCount      int32          `json:"retry_count"`
	LikesCount      int32          `json:"likes_count"`
	ViewsCount      int32          `json:"views_count"`
	CommentsCount   int32          `json:"comments_count"`
	CreatedAt       time.Time      `json:"created_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	UserID2         uuid.UUID      `json:"user_id_2"`
	UserZitadelID   string         `json:"user_zitadel_id"`
	UserUsername    string         `json:"user_username"`
	UserDisplayName sql.NullString `json:"user_display_name"`
	UserAvatarUrl   sql.NullString `json:"user_avatar_url"`
	UserIsPrivate   bool           `json:"user_is_private"`
	LikedByMe       bool           `json:"liked_by_me"`
}

// Joins the owner user row and adds liked_by_me for the
// requesting viewer (NULL viewer = not authenticated).
func (q *Queries) GetVideoDetail(ctx context.Context, arg GetVideoDetailParams) (GetVideoDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getVideoDetail, arg.ID, arg.ViewerID)
	var i GetVideoDetailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UserID2,
		&i.UserZitadelID,
		&i.UserUsername,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserIsPrivate,
		&i.LikedByMe,
	)
	return i, err
}

const getVideoStatusByID = `-- name: GetVideoStatusByID :one
SELECT id, user_id, status, retry_count, created_at, deleted_at
FROM videos
WHERE id = $1
LIMIT 1
`

type GetVideoStatusByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Status     string       `json:"status"`
	RetryCount int32        `json:"retry_count"`
	CreatedAt  time.Time    `json:"created_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetVideoStatusByID(ctx context.Context, id uuid.UUID) (GetVideoStatusByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVideoStatusByID, id)
	var i GetVideoStatusByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementCommentsCount = `-- name: IncrementCommentsCount :exec
UPDATE videos
SET comments_count = comments_count + 1
WHERE id = $1
`

func (q *Queries) IncrementCommentsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCommentsCount, id)
	return err
}

const incrementLikesCount = `-- name: IncrementLikesCount :exec
UPDATE videos
SET likes_count = likes_count + 1
WHERE id = $1
`

// Called inside the same tx as INSERT INTO likes.
func (q *Queries) IncrementLikesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementLikesCount, id)
	return err
}

const incrementVideoRetry = `-- name: IncrementVideoRetry :one
UPDATE videos
SET retry_count = retry_count + 1
WHERE id = $1 AND status IN ('PROCESSING','PENDING_UPLOAD')
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

func (q *Queries) IncrementVideoRetry(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, incrementVideoRetry, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementViews = `-- name: IncrementViews :exec
UPDATE videos
SET views_count = views_count + 1
WHERE id = $1
`

// FR-FEED-05: no per-user deduplication, just +1.
func (q *Queries) IncrementViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementViews, id)
	return err
}

const insertComment = `-- name: InsertComment :one

INSERT INTO comments (video_id, user_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, video_id, user_id, parent_id, content, created_at
`

type InsertCommentParams struct {
	VideoID  uuid.UUID     `json:"video_id"`
	UserID   uuid.UUID     `json:"user_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
	Content  string        `json:"content"`
}

// =====================================================
// comments
// =====================================================
func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, insertComment,
		arg.VideoID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.UserID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertLike = `-- name: InsertLike :one

INSERT INTO likes (user_id, video_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING user_id, video_id, created_at
`

type InsertLikeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

// =====================================================
// likes
// =====================================================
func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, insertLike, arg.UserID, arg.VideoID)
	var i Like
	err := row.Scan(&i.UserID, &i.VideoID, &i.CreatedAt)
	return i, err
}

const insertNotification = `-- name: InsertNotification :one

INSERT INTO notifications (user_id, actor_id, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, actor_id, type, payload, is_read, created_at
`

type InsertNotificationParams struct {
	UserID  uuid.UUID       `json:"user_id"`
	ActorID uuid.UUID       `json:"actor_id"`
	Type    string          `json:"type"`
	Payload json.RawMessage `json:"payload"`
}

// =====================================================
// notifications
// =====================================================
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, insertNotification,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.Type,
		&i.Payload,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const insertVideo = `-- name: InsertVideo :one

INSERT INTO videos (user_id, r2_key, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type InsertVideoParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	R2Key       string         `json:"r2_key"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
}

// =====================================================
// videos
// =====================================================
// Creates a new PENDING_UPLOAD row. r2_key MUST be unique.
func (q *Queries) InsertVideo(ctx context.Context, arg InsertVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, insertVideo,
		arg.UserID,
		arg.R2Key,
		arg.Title,
		arg.Description,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND followee_id = $2
)
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isLiked = `-- name: IsLiked :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE user_id = $1 AND video_id = $2
)
`

type IsLikedParams struct {
	UserID  uuid.UUID `json:"user_id"`
	VideoID uuid.UUID `json:"video_id"`
}

func (q *Queries) IsLiked(ctx context.Context, arg IsLikedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isLiked, arg.UserID, arg.VideoID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCommentsByVideo = `-- name: ListCommentsByVideo :many
SELECT
    c.id,
    c.video_id,
    c.user_id,
    c.parent_id,
    c.content,
    c.created_at,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private
FROM comments c
JOIN users u ON u.id = c.user_id
WHERE c.video_id = $1
  AND ($2::timestamptz IS NULL
       OR (c.created_at, c.id) < ($2::timestamptz, $3::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $4
`

type ListCommentsByVideoParams struct {
	VideoID       uuid.UUID     `json:"video_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListCommentsByVideoRow struct {
	ID          uuid.UUID      `json:"id"`
	VideoID     uuid.UUID      `json:"video_id"`
	UserID      uuid.UUID      `json:"user_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Content     string         `json:"content"`
	CreatedAt   time.Time      `json:"created_at"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
}

// Flat list of comments for a video, cursor pagination.
// Joins user for author info.
func (q *Queries) ListCommentsByVideo(ctx context.Context, arg ListCommentsByVideoParams) ([]ListCommentsByVideoRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByVideo,
		arg.VideoID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByVideoRow{}
	for rows.Next() {
		var i ListCommentsByVideoRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.UserID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedVideos = `-- name: ListFeedVideos :many
SELECT v.id, v.user_id, v.title, v.description, v.r2_key, v.hls_prefix, v.thumbnail_key, v.duration_seconds, v.status, v.retry_count, v.likes_count, v.views_count, v.comments_count, v.created_at, v.deleted_at
FROM videos v
JOIN users u ON u.id = v.user_id
WHERE v.status = 'READY'
  AND v.user_id <> $1
  AND u.is_active = TRUE
  AND (u.is_private = FALSE
       OR EXISTS (
           SELECT 1 FROM follows f
           WHERE f.follower_id = $1 AND f.followee_id = u.id
       ))
  AND ($2::timestamptz IS NULL
       OR (v.created_at, v.id) < ($2::timestamptz, $3::uuid))
ORDER BY v.created_at DESC, v.id DESC
LIMIT $4
`

type ListFeedVideosParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// FR-FEED-01: status=READY, owner active, exclude self,
// include public accounts + accounts the viewer follows.
// Cursor pagination uses (created_at, id) < ($3, $4).
func (q *Queries) ListFeedVideos(ctx context.Context, arg ListFeedVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listFeedVideos,
		arg.UserID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
			&i.DurationSeconds,
			&i.Status,
			&i.RetryCount,
			&i.LikesCount,
			&i.ViewsCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT
    f.follower_id AS id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private,
    f.created_at,
    EXISTS (
        SELECT 1 FROM follows f2
        WHERE f2.follower_id = $1 AND f2.followee_id = f.follower_id
    ) AS is_following_back
FROM follows f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $2
  AND ($3::timestamptz IS NULL
       OR (f.created_at, f.follower_id) < ($3::timestamptz, $4::uuid))
ORDER BY f.created_at DESC, f.follower_id DESC
LIMIT $5
`

type ListFollowersParams struct {
	FollowerID    uuid.UUID     `json:"follower_id"`
	FolloweeID    uuid.UUID     `json:"followee_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListFollowersRow struct {
	ID              uuid.UUID      `json:"id"`
	Username        string         `json:"username"`
	DisplayName     sql.NullString `json:"display_name"`
	AvatarUrl       sql.NullString `json:"avatar_url"`
	IsPrivate       bool           `json:"is_private"`
	CreatedAt       time.Time      `json:"created_at"`
	IsFollowingBack bool           `json:"is_following_back"`
}

// Returns followers of followee_id with user profile fields.
// Cursor pagination: (f.created_at, f.follower_id) < ($3, $4).
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowers,
		arg.FollowerID,
		arg.FolloweeID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.IsFollowingBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
    f.followee_id AS id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private,
    f.created_at
FROM follows f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $1
  AND ($2::timestamptz IS NULL
       OR (f.created_at, f.followee_id) < ($2::timestamptz, $3::uuid))
ORDER BY f.created_at DESC, f.followee_id DESC
LIMIT $4
`

type ListFollowingParams struct {
	FollowerID    uuid.UUID     `json:"follower_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

type ListFollowingRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
	CreatedAt   time.Time      `json:"created_at"`
}

// Returns users that follower_id is following.
func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowing,
		arg.FollowerID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, actor_id, type, payload, is_read, created_at
FROM notifications
WHERE user_id = $1
  AND ($2::timestamptz IS NULL
       OR (created_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListNotificationsParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// All notifications for a user, newest first, cursor pagination.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.UserID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.Type,
			&i.Payload,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoKeysByUser = `-- name: ListVideoKeysByUser :many
SELECT id, r2_key, hls_prefix, thumbnail_key
FROM videos
WHERE user_id = $1
`

type ListVideoKeysByUserRow struct {
	ID           uuid.UUID      `json:"id"`
	R2Key        string         `json:"r2_key"`
	HlsPrefix    sql.NullString `json:"hls_prefix"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
}

// Returns the r2 object keys that must be deleted from R2
// when the user is tombstoned. hls_prefix is a folder, so
// the worker uses it to list + delete every object under
// that prefix.
func (q *Queries) ListVideoKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListVideoKeysByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listVideoKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoKeysByUserRow{}
	for rows.Next() {
		var i ListVideoKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByUser = `-- name: ListVideosByUser :many
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE user_id = $1
  AND ($2::boolean = TRUE  AND status <> 'DELETED'
       OR $2::boolean = FALSE AND status = 'READY')
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListVideosByUserParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	IsOwner       bool          `json:"is_owner"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// Owner sees all rows except DELETED. Non-owner sees only
// READY. The caller decides which branch by branching on
// (is_owner).
func (q *Queries) ListVideosByUser(ctx context.Context, arg ListVideosByUserParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByUser,
		arg.UserID,
		arg.IsOwner,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
			&i.DurationSeconds,
			&i.Status,
			&i.RetryCount,
			&i.LikesCount,
			&i.ViewsCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosEligibleForCleanup = `-- name: ListVideosEligibleForCleanup :many
SELECT id, user_id, r2_key, hls_prefix, thumbnail_key
FROM videos
WHERE status = 'DELETED'
  AND deleted_at < NOW() - INTERVAL '24 hours'
ORDER BY deleted_at ASC
LIMIT $1
`

type ListVideosEligibleForCleanupRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	R2Key        string         `json:"r2_key"`
	HlsPrefix    sql.NullString `json:"hls_prefix"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
}

// NFR-13: 24-hour grace period after DELETED.
func (q *Queries) ListVideosEligibleForCleanup(ctx context.Context, limit int32) ([]ListVideosEligibleForCleanupRow, error) {
	rows, err := q.db.QueryContext(ctx, listVideosEligibleForCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosEligibleForCleanupRow{}
	for rows.Next() {
		var i ListVideosEligibleForCleanupRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markVideoDeleted = `-- name: MarkVideoDeleted :one
UPDATE videos
SET status = 'DELETED', deleted_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type MarkVideoDeletedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Soft delete: status -> DELETED, deleted_at -> NOW().
// chk_videos_deleted_at forces deleted_at to be set.
func (q *Queries) MarkVideoDeleted(ctx context.Context, arg MarkVideoDeletedParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoDeleted, arg.ID, arg.UserID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markVideoFailed = `-- name: MarkVideoFailed :one
UPDATE videos
SET status = 'FAILED'
WHERE id = $1
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

func (q *Queries) MarkVideoFailed(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoFailed, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markVideoReady = `-- name: MarkVideoReady :one
UPDATE videos
SET status = 'READY',
    hls_prefix = $2,
    thumbnail_key = $3,
    duration_seconds = $4
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type MarkVideoReadyParams struct {
	ID              uuid.UUID      `json:"id"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
}

// Called by the worker after a successful transcode. The
// WHERE clause guards against overwriting a row that has
// been deleted while the worker was busy (FR-VIDEO-08).
func (q *Queries) MarkVideoReady(ctx context.Context, arg MarkVideoReadyParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoReady,
		arg.ID,
		arg.HlsPrefix,
		arg.ThumbnailKey,
		arg.DurationSeconds,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const tombstoneUser = `-- name: TombstoneUser :one
UPDATE users
SET is_active     = FALSE,
    deleted_at    = NOW(),
    username      = 'deleted_' || id::text,
    display_name  = NULL,
    bio           = NULL,
    avatar_url    = NULL
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

// Triggered by user.removed. Username is replaced with a
// deterministic placeholder so the UNIQUE constraint on
// username keeps holding; PII is nulled out.
func (q *Queries) TombstoneUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, tombstoneUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePendingVideoR2Key = `-- name: UpdatePendingVideoR2Key :one
UPDATE videos
SET r2_key = $2
WHERE id = $1 AND status = 'PENDING_UPLOAD'
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type UpdatePendingVideoR2KeyParams struct {
	ID    uuid.UUID `json:"id"`
	R2Key string    `json:"r2_key"`
}

// When upload-intent is called again, rotate r2_key on
// the existing PENDING_UPLOAD row. The partial unique
// index makes the r2_key UNIQUE constraint safe.
func (q *Queries) UpdatePendingVideoR2Key(ctx context.Context, arg UpdatePendingVideoR2KeyParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updatePendingVideoR2Key, arg.ID, arg.R2Key)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    bio          = COALESCE($3,          bio),
    avatar_url   = COALESCE($4,   avatar_url),
    is_private   = COALESCE($5,   is_private)
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   sql.NullBool   `json:"is_private"`
}

// All fields are optional; only non-NULL params are written.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.IsPrivate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateVideoToProcessing = `-- name: UpdateVideoToProcessing :one
UPDATE videos
SET status = 'PROCESSING', retry_count = 0
WHERE id = $1
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

// Used by the retry path: set status back to PROCESSING
// and reset retry_count.
func (q *Queries) UpdateVideoToProcessing(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoToProcessing, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
