// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const searchUsers = `-- name: SearchUsers :many

SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.is_private
FROM users u
WHERE u.is_active = TRUE
  AND u.id <> $1
  AND (u.username ILIKE '%' || $2::text || '%' OR u.display_name ILIKE '%' || $2::text || '%')
ORDER BY
    (LOWER(u.username) = LOWER($3::text)) DESC,
    length(u.username) ASC,
    COALESCE((SELECT count(*) FROM follows f WHERE f.followee_id = u.id), 0) DESC,
    u.username ASC
LIMIT $5 OFFSET $4
`

type SearchUsersParams struct {
	ViewerID     uuid.UUID `json:"viewer_id"`
	QueryPattern string    `json:"query_pattern"`
	RawQuery     string    `json:"raw_query"`
	PageOffset   int32     `json:"page_offset"`
	PageLimit    int32     `json:"page_limit"`
}

type SearchUsersRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   bool           `json:"is_private"`
}

// =====================================================
// queries/search.sql
// Search queries for users and videos.
// See planning/ROADMAP_TIKTOK_PARITY.md §3 and Issue #57.
// =====================================================
// Searches active users by username or display_name (case-insensitive).
// Excludes tombstoned users and the requesting viewer itself.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers,
		arg.ViewerID,
		arg.QueryPattern,
		arg.RawQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVideos = `-- name: SearchVideos :many
SELECT
    v.id, v.user_id, v.title, v.description, v.r2_key,
    v.hls_prefix, v.thumbnail_key, v.duration_seconds,
    v.status, v.retry_count, v.likes_count, v.views_count,
    v.comments_count, v.created_at, v.deleted_at,
    u.id            AS user_id_2,
    u.username      AS user_username,
    u.display_name  AS user_display_name,
    u.avatar_url    AS user_avatar_url,
    u.is_private    AS user_is_private,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.video_id = v.id AND l.user_id = $1
    ) AS liked_by_me
FROM videos v
JOIN users u ON u.id = v.user_id
WHERE v.status = 'READY'
  AND v.deleted_at IS NULL
  AND u.is_active = TRUE
  AND (v.title ILIKE '%' || $2::text || '%' OR v.description ILIKE '%' || $2::text || '%')
  AND (u.is_private = FALSE
       OR u.id = $1
       OR EXISTS (
           SELECT 1 FROM follows f
           WHERE f.follower_id = $1 AND f.followee_id = u.id
       ))
ORDER BY v.views_count DESC, v.created_at DESC, v.id DESC
LIMIT $4 OFFSET $3
`

type SearchVideosParams struct {
	ViewerID     uuid.UUID `json:"viewer_id"`
	QueryPattern string    `json:"query_pattern"`
	PageOffset   int32     `json:"page_offset"`
	PageLimit    int32     `json:"page_limit"`
}

type SearchVideosRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	R2Key           string         `json:"r2_key"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	RetryCount      int32          `json:"retry_count"`
	LikesCount      int32          `json:"likes_count"`
	ViewsCount      int32          `json:"views_count"`
	CommentsCount   int32          `json:"comments_count"`
	CreatedAt       time.Time      `json:"created_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	UserID2         uuid.UUID      `json:"user_id_2"`
	UserUsername    string         `json:"user_username"`
	UserDisplayName sql.NullString `json:"user_display_name"`
	UserAvatarUrl   sql.NullString `json:"user_avatar_url"`
	UserIsPrivate   bool           `json:"user_is_private"`
	LikedByMe       bool           `json:"liked_by_me"`
}

// Searches READY videos by title or description (case-insensitive).
// Enforces active owner user, deleted_at NULL, and private user visibility rule (public, owner self, or followed).
func (q *Queries) SearchVideos(ctx context.Context, arg SearchVideosParams) ([]SearchVideosRow, error) {
	rows, err := q.db.QueryContext(ctx, searchVideos,
		arg.ViewerID,
		arg.QueryPattern,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVideosRow{}
	for rows.Next() {
		var i SearchVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
			&i.DurationSeconds,
			&i.Status,
			&i.RetryCount,
			&i.LikesCount,
			&i.ViewsCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.UserID2,
			&i.UserUsername,
			&i.UserDisplayName,
			&i.UserAvatarUrl,
			&i.UserIsPrivate,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
