// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (zitadel_id, username, display_name)
VALUES ($1, $2, $3)
ON CONFLICT (zitadel_id) DO NOTHING
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

type CreateUserParams struct {
	ZitadelID   string         `json:"zitadel_id"`
	Username    string         `json:"username"`
	DisplayName sql.NullString `json:"display_name"`
}

// get-or-create: on conflict do nothing. Caller re-selects
// the row when INSERT returns nothing.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ZitadelID, arg.Username, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :one
UPDATE users
SET is_active  = FALSE,
    deleted_at = COALESCE(deleted_at, NOW())
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

// Triggered by webhook event user.deactivated.
func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, deactivateUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByZitadelID = `-- name: GetUserByZitadelID :one

SELECT id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
FROM users
WHERE zitadel_id = $1
LIMIT 1
`

// =====================================================
// queries/users.sql
// User-related queries. Split from queries.sql (single
// file) on phase-1.5 to keep each table's query surface
// in its own file for easier review and maintenance.
// See sqlc.yaml: queries: "queries" picks up every
// *.sql file under sqlc/queries/ in alphabetical order.
// =====================================================
// Used by the auth middleware get-or-create flow.
func (q *Queries) GetUserByZitadelID(ctx context.Context, zitadelID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByZitadelID, zitadelID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProfileWithStats = `-- name: GetUserProfileWithStats :one
SELECT
    u.id, u.zitadel_id, u.username, u.display_name, u.bio, u.avatar_url, u.is_private, u.is_active, u.deleted_at, u.created_at,
    (SELECT COUNT(*) FROM follows f WHERE f.followee_id = u.id) AS follower_count,
    (SELECT COUNT(*) FROM follows f WHERE f.follower_id = u.id) AS following_count,
    EXISTS (
        SELECT 1
        FROM follows f
        WHERE f.follower_id = $2 AND f.followee_id = u.id
    ) AS is_following
FROM users u
WHERE u.id = $1
LIMIT 1
`

type GetUserProfileWithStatsParams struct {
	ID         uuid.UUID `json:"id"`
	FollowerID uuid.UUID `json:"follower_id"`
}

type GetUserProfileWithStatsRow struct {
	ID             uuid.UUID      `json:"id"`
	ZitadelID      string         `json:"zitadel_id"`
	Username       string         `json:"username"`
	DisplayName    sql.NullString `json:"display_name"`
	Bio            sql.NullString `json:"bio"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	IsPrivate      bool           `json:"is_private"`
	IsActive       bool           `json:"is_active"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	CreatedAt      time.Time      `json:"created_at"`
	FollowerCount  int64          `json:"follower_count"`
	FollowingCount int64          `json:"following_count"`
	IsFollowing    bool           `json:"is_following"`
}

// Profile + follower/following counts + is_following for
// the requesting viewer. Returns NULL for
// is_following when the viewer is the same as the
// profile owner.
func (q *Queries) GetUserProfileWithStats(ctx context.Context, arg GetUserProfileWithStatsParams) (GetUserProfileWithStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileWithStats, arg.ID, arg.FollowerID)
	var i GetUserProfileWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.FollowerCount,
		&i.FollowingCount,
		&i.IsFollowing,
	)
	return i, err
}

const tombstoneUser = `-- name: TombstoneUser :one
UPDATE users
SET is_active     = FALSE,
    deleted_at    = NOW(),
    username      = 'deleted_' || id::text,
    display_name  = NULL,
    bio           = NULL,
    avatar_url    = NULL
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

// Triggered by user.removed. Username is replaced with a
// deterministic placeholder so the UNIQUE constraint on
// username keeps holding; PII is nulled out.
func (q *Queries) TombstoneUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, tombstoneUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    display_name = COALESCE($2, display_name),
    bio          = COALESCE($3,          bio),
    avatar_url   = COALESCE($4,   avatar_url),
    is_private   = COALESCE($5,   is_private)
WHERE id = $1
RETURNING id, zitadel_id, username, display_name, bio, avatar_url, is_private, is_active, deleted_at, created_at
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	DisplayName sql.NullString `json:"display_name"`
	Bio         sql.NullString `json:"bio"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	IsPrivate   sql.NullBool   `json:"is_private"`
}

// All fields are optional; only non-NULL params are written.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.IsPrivate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ZitadelID,
		&i.Username,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.IsPrivate,
		&i.IsActive,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}
