// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const confirmVideoProcessing = `-- name: ConfirmVideoProcessing :one
UPDATE videos
SET status = 'PROCESSING', retry_count = 0
WHERE id = $1
  AND user_id = $2
  AND status = 'PENDING_UPLOAD'
  AND r2_key = $3
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type ConfirmVideoProcessingParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	R2Key  string    `json:"r2_key"`
}

// Atomic transition PENDING_UPLOAD -> PROCESSING. Returns
// the updated row only when the ownership + r2_key + status
// all match. Used by POST /api/videos/confirm.
func (q *Queries) ConfirmVideoProcessing(ctx context.Context, arg ConfirmVideoProcessingParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, confirmVideoProcessing, arg.ID, arg.UserID, arg.R2Key)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementCommentsCount = `-- name: DecrementCommentsCount :exec
UPDATE videos
SET comments_count = comments_count - 1
WHERE id = $1 AND comments_count > 0
`

func (q *Queries) DecrementCommentsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCommentsCount, id)
	return err
}

const decrementCommentsForUser = `-- name: DecrementCommentsForUser :exec
UPDATE videos
SET comments_count = GREATEST(comments_count - 1, 0)
WHERE id IN (
    SELECT c.video_id FROM comments c WHERE c.user_id = $1
)
`

func (q *Queries) DecrementCommentsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementCommentsForUser, userID)
	return err
}

const decrementLikesCount = `-- name: DecrementLikesCount :exec
UPDATE videos
SET likes_count = likes_count - 1
WHERE id = $1 AND likes_count > 0
`

// Called inside the same tx as DELETE FROM likes. Guarded
// by >= 1 to keep the chk_videos_counters check happy.
func (q *Queries) DecrementLikesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementLikesCount, id)
	return err
}

const decrementLikesForUser = `-- name: DecrementLikesForUser :exec
UPDATE videos
SET likes_count = GREATEST(likes_count - 1, 0)
WHERE id IN (SELECT l.video_id FROM likes l WHERE l.user_id = $1)
`

// Called by DeleteUserData to keep the denormalized
// counter accurate after a user is tombstoned.
func (q *Queries) DecrementLikesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementLikesForUser, userID)
	return err
}

const deleteVideoRow = `-- name: DeleteVideoRow :exec
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideoRow(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideoRow, id)
	return err
}

const deleteVideosByUser = `-- name: DeleteVideosByUser :exec
DELETE FROM videos WHERE user_id = $1
`

// Called from DeleteUserData AFTER the r2 keys are
// enqueued for cleanup. videos.user_id has ON DELETE
// CASCADE so this is mostly defensive.
func (q *Queries) DeleteVideosByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideosByUser, userID)
	return err
}

const getPendingVideoByUser = `-- name: GetPendingVideoByUser :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE user_id = $1 AND status = 'PENDING_UPLOAD'
LIMIT 1
`

// Used by upload-intent to reuse / replace an existing
// PENDING_UPLOAD record.
func (q *Queries) GetPendingVideoByUser(ctx context.Context, userID uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getPendingVideoByUser, userID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetVideoByID(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoByIDForUpdate = `-- name: GetVideoByIDForUpdate :one
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE id = $1
FOR UPDATE
`

// Caller MUST be inside a transaction.
func (q *Queries) GetVideoByIDForUpdate(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByIDForUpdate, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVideoDetail = `-- name: GetVideoDetail :one
SELECT
    v.id, v.user_id, v.title, v.description, v.r2_key, v.hls_prefix, v.thumbnail_key, v.duration_seconds, v.status, v.retry_count, v.likes_count, v.views_count, v.comments_count, v.created_at, v.deleted_at,
    u.id            AS user_id_2,
    u.zitadel_id    AS user_zitadel_id,
    u.username      AS user_username,
    u.display_name  AS user_display_name,
    u.avatar_url    AS user_avatar_url,
    u.is_private    AS user_is_private,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.video_id = v.id AND l.user_id = $2
    ) AS liked_by_me
FROM videos v
JOIN users u ON u.id = v.user_id
WHERE v.id = $1
LIMIT 1
`

type GetVideoDetailParams struct {
	ID       uuid.UUID     `json:"id"`
	ViewerID uuid.NullUUID `json:"viewer_id"`
}

type GetVideoDetailRow struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Title           sql.NullString `json:"title"`
	Description     sql.NullString `json:"description"`
	R2Key           string         `json:"r2_key"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
	Status          string         `json:"status"`
	RetryCount      int32          `json:"retry_count"`
	LikesCount      int32          `json:"likes_count"`
	ViewsCount      int32          `json:"views_count"`
	CommentsCount   int32          `json:"comments_count"`
	CreatedAt       time.Time      `json:"created_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	UserID2         uuid.UUID      `json:"user_id_2"`
	UserZitadelID   string         `json:"user_zitadel_id"`
	UserUsername    string         `json:"user_username"`
	UserDisplayName sql.NullString `json:"user_display_name"`
	UserAvatarUrl   sql.NullString `json:"user_avatar_url"`
	UserIsPrivate   bool           `json:"user_is_private"`
	LikedByMe       bool           `json:"liked_by_me"`
}

// Joins the owner user row and adds liked_by_me for the
// requesting viewer (NULL viewer = not authenticated).
func (q *Queries) GetVideoDetail(ctx context.Context, arg GetVideoDetailParams) (GetVideoDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getVideoDetail, arg.ID, arg.ViewerID)
	var i GetVideoDetailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UserID2,
		&i.UserZitadelID,
		&i.UserUsername,
		&i.UserDisplayName,
		&i.UserAvatarUrl,
		&i.UserIsPrivate,
		&i.LikedByMe,
	)
	return i, err
}

const getVideoStatusByID = `-- name: GetVideoStatusByID :one
SELECT id, user_id, status, retry_count, created_at, deleted_at
FROM videos
WHERE id = $1
LIMIT 1
`

type GetVideoStatusByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	Status     string       `json:"status"`
	RetryCount int32        `json:"retry_count"`
	CreatedAt  time.Time    `json:"created_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
}

func (q *Queries) GetVideoStatusByID(ctx context.Context, id uuid.UUID) (GetVideoStatusByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getVideoStatusByID, id)
	var i GetVideoStatusByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementCommentsCount = `-- name: IncrementCommentsCount :exec
UPDATE videos
SET comments_count = comments_count + 1
WHERE id = $1
`

func (q *Queries) IncrementCommentsCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementCommentsCount, id)
	return err
}

const incrementLikesCount = `-- name: IncrementLikesCount :exec
UPDATE videos
SET likes_count = likes_count + 1
WHERE id = $1
`

// Called inside the same tx as INSERT INTO likes.
func (q *Queries) IncrementLikesCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementLikesCount, id)
	return err
}

const incrementVideoRetry = `-- name: IncrementVideoRetry :one
UPDATE videos
SET retry_count = retry_count + 1
WHERE id = $1 AND status IN ('PROCESSING','PENDING_UPLOAD')
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

func (q *Queries) IncrementVideoRetry(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, incrementVideoRetry, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementViews = `-- name: IncrementViews :exec
UPDATE videos
SET views_count = views_count + 1
WHERE id = $1
`

// FR-FEED-05: no per-user deduplication, just +1.
func (q *Queries) IncrementViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementViews, id)
	return err
}

const insertVideo = `-- name: InsertVideo :one

INSERT INTO videos (user_id, r2_key, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type InsertVideoParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	R2Key       string         `json:"r2_key"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
}

// =====================================================
// queries/videos.sql
// Video-related queries. See sqlc/queries/users.sql header
// for context on the per-table split.
// =====================================================
// Creates a new PENDING_UPLOAD row. r2_key MUST be unique.
func (q *Queries) InsertVideo(ctx context.Context, arg InsertVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, insertVideo,
		arg.UserID,
		arg.R2Key,
		arg.Title,
		arg.Description,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFeedVideos = `-- name: ListFeedVideos :many
SELECT v.id, v.user_id, v.title, v.description, v.r2_key, v.hls_prefix, v.thumbnail_key, v.duration_seconds, v.status, v.retry_count, v.likes_count, v.views_count, v.comments_count, v.created_at, v.deleted_at
FROM videos v
JOIN users u ON u.id = v.user_id
WHERE v.status = 'READY'
  AND v.user_id <> $1
  AND u.is_active = TRUE
  AND (u.is_private = FALSE
       OR EXISTS (
           SELECT 1 FROM follows f
           WHERE f.follower_id = $1 AND f.followee_id = u.id
       ))
  AND ($2::timestamptz IS NULL
       OR (v.created_at, v.id) < ($2::timestamptz, $3::uuid))
ORDER BY v.created_at DESC, v.id DESC
LIMIT $4
`

type ListFeedVideosParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// FR-FEED-01: status=READY, owner active, exclude self,
// include public accounts + accounts the viewer follows.
// Cursor pagination uses (created_at, id) < ($3, $4).
func (q *Queries) ListFeedVideos(ctx context.Context, arg ListFeedVideosParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listFeedVideos,
		arg.UserID,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
			&i.DurationSeconds,
			&i.Status,
			&i.RetryCount,
			&i.LikesCount,
			&i.ViewsCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideoKeysByUser = `-- name: ListVideoKeysByUser :many
SELECT id, r2_key, hls_prefix, thumbnail_key
FROM videos
WHERE user_id = $1
`

type ListVideoKeysByUserRow struct {
	ID           uuid.UUID      `json:"id"`
	R2Key        string         `json:"r2_key"`
	HlsPrefix    sql.NullString `json:"hls_prefix"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
}

// Returns the r2 object keys that must be deleted from R2
// when the user is tombstoned. hls_prefix is a folder, so
// the worker uses it to list + delete every object under
// that prefix.
func (q *Queries) ListVideoKeysByUser(ctx context.Context, userID uuid.UUID) ([]ListVideoKeysByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listVideoKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideoKeysByUserRow{}
	for rows.Next() {
		var i ListVideoKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosByUser = `-- name: ListVideosByUser :many
SELECT id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
FROM videos
WHERE user_id = $1
  AND ($2::boolean = TRUE  AND status <> 'DELETED'
       OR $2::boolean = FALSE AND status = 'READY')
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListVideosByUserParams struct {
	UserID        uuid.UUID     `json:"user_id"`
	IsOwner       bool          `json:"is_owner"`
	CursorCreated sql.NullTime  `json:"cursor_created"`
	CursorID      uuid.NullUUID `json:"cursor_id"`
	PageLimit     int32         `json:"page_limit"`
}

// Owner sees all rows except DELETED. Non-owner sees only
// READY. The caller decides which branch by branching on
// (is_owner).
func (q *Queries) ListVideosByUser(ctx context.Context, arg ListVideosByUserParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, listVideosByUser,
		arg.UserID,
		arg.IsOwner,
		arg.CursorCreated,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
			&i.DurationSeconds,
			&i.Status,
			&i.RetryCount,
			&i.LikesCount,
			&i.ViewsCount,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosEligibleForCleanup = `-- name: ListVideosEligibleForCleanup :many
SELECT id, user_id, r2_key, hls_prefix, thumbnail_key
FROM videos
WHERE status = 'DELETED'
  AND deleted_at < NOW() - INTERVAL '24 hours'
ORDER BY deleted_at ASC
LIMIT $1
`

type ListVideosEligibleForCleanupRow struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	R2Key        string         `json:"r2_key"`
	HlsPrefix    sql.NullString `json:"hls_prefix"`
	ThumbnailKey sql.NullString `json:"thumbnail_key"`
}

// NFR-13: 24-hour grace period after DELETED.
func (q *Queries) ListVideosEligibleForCleanup(ctx context.Context, limit int32) ([]ListVideosEligibleForCleanupRow, error) {
	rows, err := q.db.QueryContext(ctx, listVideosEligibleForCleanup, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVideosEligibleForCleanupRow{}
	for rows.Next() {
		var i ListVideosEligibleForCleanupRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.R2Key,
			&i.HlsPrefix,
			&i.ThumbnailKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVideoDeleted = `-- name: MarkVideoDeleted :one
UPDATE videos
SET status = 'DELETED', deleted_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type MarkVideoDeletedParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Soft delete: status -> DELETED, deleted_at -> NOW().
// chk_videos_deleted_at forces deleted_at to be set.
func (q *Queries) MarkVideoDeleted(ctx context.Context, arg MarkVideoDeletedParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoDeleted, arg.ID, arg.UserID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markVideoFailed = `-- name: MarkVideoFailed :one
UPDATE videos
SET status = 'FAILED'
WHERE id = $1
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

func (q *Queries) MarkVideoFailed(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoFailed, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const markVideoReady = `-- name: MarkVideoReady :one
UPDATE videos
SET status = 'READY',
    hls_prefix = $2,
    thumbnail_key = $3,
    duration_seconds = $4
WHERE id = $1 AND status = 'PROCESSING'
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type MarkVideoReadyParams struct {
	ID              uuid.UUID      `json:"id"`
	HlsPrefix       sql.NullString `json:"hls_prefix"`
	ThumbnailKey    sql.NullString `json:"thumbnail_key"`
	DurationSeconds sql.NullInt32  `json:"duration_seconds"`
}

// Called by the worker after a successful transcode. The
// WHERE clause guards against overwriting a row that has
// been deleted while the worker was busy (FR-VIDEO-08).
func (q *Queries) MarkVideoReady(ctx context.Context, arg MarkVideoReadyParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, markVideoReady,
		arg.ID,
		arg.HlsPrefix,
		arg.ThumbnailKey,
		arg.DurationSeconds,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePendingVideoMetadata = `-- name: UpdatePendingVideoMetadata :one
UPDATE videos
SET title = $2,
    description = $3
WHERE id = $1 AND status = 'PENDING_UPLOAD'
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type UpdatePendingVideoMetadataParams struct {
	ID          uuid.UUID      `json:"id"`
	Title       sql.NullString `json:"title"`
	Description sql.NullString `json:"description"`
}

// Refresh title/description on an existing
// PENDING_UPLOAD row when upload-intent is called
// again. The WHERE guard matches UpdatePendingVideoR2Key
// so a concurrent state transition (e.g. the user
// confirmed in another tab) makes the UPDATE a no-op
// (returns sql.ErrNoRows) instead of overwriting
// metadata on a row that has already moved to
// PROCESSING.
func (q *Queries) UpdatePendingVideoMetadata(ctx context.Context, arg UpdatePendingVideoMetadataParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updatePendingVideoMetadata, arg.ID, arg.Title, arg.Description)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePendingVideoR2Key = `-- name: UpdatePendingVideoR2Key :one
UPDATE videos
SET r2_key = $2
WHERE id = $1 AND status = 'PENDING_UPLOAD'
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

type UpdatePendingVideoR2KeyParams struct {
	ID    uuid.UUID `json:"id"`
	R2Key string    `json:"r2_key"`
}

// When upload-intent is called again, rotate r2_key on
// the existing PENDING_UPLOAD row. The partial unique
// index makes the r2_key UNIQUE constraint safe.
func (q *Queries) UpdatePendingVideoR2Key(ctx context.Context, arg UpdatePendingVideoR2KeyParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, updatePendingVideoR2Key, arg.ID, arg.R2Key)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateVideoToProcessing = `-- name: UpdateVideoToProcessing :one
UPDATE videos
SET status = 'PROCESSING', retry_count = 0
WHERE id = $1
RETURNING id, user_id, title, description, r2_key, hls_prefix, thumbnail_key, duration_seconds, status, retry_count, likes_count, views_count, comments_count, created_at, deleted_at
`

// Used by the retry path: set status back to PROCESSING
// and reset retry_count.
func (q *Queries) UpdateVideoToProcessing(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, updateVideoToProcessing, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.R2Key,
		&i.HlsPrefix,
		&i.ThumbnailKey,
		&i.DurationSeconds,
		&i.Status,
		&i.RetryCount,
		&i.LikesCount,
		&i.ViewsCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
